#!/bin/bash

source ./menus.sh
source ./table-manager.sh
source ./database-manager.sh
source ./screen.sh

BASE_DIR="$(pwd)/databases"

if [ ! -d "$BASE_DIR" ]; then
  mkdir "$BASE_DIR"
fi  

introScreen

mainMenu
